version: '3.8'
services: 
  db:
    image: mysql:8.0
    container_name: mysql_db
    environment:
      MYSQL_ROOT_PASSWORD: test
      MYSQL_DATABASE: filmpedia_database
    ports: 
      - "3306:3306"
    volumes: 
      - mysql_data:/var/lib/mysql
  wordpress:
    image: wordpress
    container_name: wordpress_app
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_NAME: filmpedia_database
      WORDPRESS_DB_USER: root
      WORDPRESS_DB_PASSWORD: test
    ports:
      - "8080:80"
    volumes:
      - wordpress_data:/var/www/html
      - ./wp-content:/var/www/html/wp-content
    depends_on:
      - db
volumes:
  mysql_data:
  wordpress_data:

